apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: uvc-de-monitoring-tls
  namespace: default
spec:
  secretName: uvc-de-monitoring-tls
  duration: 2160h
  renewBefore: 360h
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: 'monitoring.univocal.de'
  dnsNames:
  - 'monitoring.univocal.de'