# Package file /etc/httpd/conf.d/shib.conf is removed in the image to avoid duplicate
# <Location> blocks with the mounted shib-proxy.conf. Only load mod_shib here.
LoadModule mod_shib /usr/lib64/shibboleth/mod_shib_24.so
ShibConfig /etc/shibboleth/shibboleth2.xml
ShibCompatValidUser On
