apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - shibboleth-apache-configmap.yaml
  - shibboleth-configmap.yaml
  - uvc-auth-depl.yaml
  - uvc-shibboleth-depl.yaml
  - uvc-tenant-depl.yaml
  - uvc-survey-depl.yaml
  - uvc-project-depl.yaml
  - uvc-profile-depl.yaml
  - uvc-knowledge-depl.yaml
  - uvc-event-depl.yaml
  - uvc-chat-depl.yaml
  - uvc-calendar-depl.yaml
  - uvc-ingress-srv.yaml
  - uvc-web-depl.yaml
  - uvc-landing-depl.yaml
  - uvc-redis-depl.yaml

commonLabels:
  app.kubernetes.io/managed-by: kustomize
  app.kubernetes.io/part-of: uvc
  uvc/env: dev

commonAnnotations:
  app.kubernetes.io/version: "2.X-dev"
  uvc/doc.version: "2.X-dev"
  uvc/doc.owner: "Kevin Saukel"