apiVersion: v1
kind: ConfigMap
metadata:
  name: shibboleth-apache-config
data:
  shib-proxy.conf: |
    LoadModule mod_shib /usr/lib64/shibboleth/mod_shib_24.so
    ShibConfig /etc/shibboleth/shibboleth2.xml
    ShibCompatValidUser On

    <VirtualHost *:80>
        ServerName ${SHIB_APACHE_SERVER_NAME}
        UseCanonicalName On

        ProxyPreserveHost On
        RequestHeader set X-Forwarded-Proto "https"
        RequestHeader set X-Forwarded-Port "443"

        DocumentRoot /var/www/html
        <Directory /var/www/html>
            Require all granted
        </Directory>

        <Location /Shibboleth.sso>
            AuthType None
            Require all granted
        </Location>

        <Location /api/auth/public/dfn/login>
            AuthType shibboleth
            ShibRequestSetting requireSession 1
            Require valid-user
        </Location>

        <Location /api/auth/public/dfn/bridge>
            AuthType shibboleth
            ShibRequestSetting requireSession 1
            Require valid-user
        </Location>

        RequestHeader unset X-Remote-User
        RequestHeader unset X-Mail
        RequestHeader unset X-Given-Name
        RequestHeader unset X-Sn
        RequestHeader unset X-Subject-Id

        RequestHeader set X-Remote-User %{REMOTE_USER}e
        RequestHeader set X-Mail %{mail}e
        RequestHeader set X-Given-Name %{givenName}e
        RequestHeader set X-Sn %{sn}e
        RequestHeader set X-Subject-Id %{subject-id}e

        ProxyPass        /api/auth/public/dfn/login http://uvc-auth-srv:3001/api/auth/public/dfn/login
        ProxyPassReverse /api/auth/public/dfn/login http://uvc-auth-srv:3001/api/auth/public/dfn/login
        ProxyPass        /api/auth/public/dfn/bridge http://uvc-auth-srv:3001/api/auth/public/dfn/bridge
        ProxyPassReverse /api/auth/public/dfn/bridge http://uvc-auth-srv:3001/api/auth/public/dfn/bridge
    </VirtualHost>
