apiVersion: apps/v1
kind: Deployment
metadata: 
  name: uvc-tenant
spec:
  replicas: 1
  selector: 
    matchLabels: 
      app: uvc-tenant
  template:
    metadata:
      labels:
        app: uvc-tenant
    spec:
      imagePullSecrets:
        - name: REGISTRY_SECRET_PLACEHOLDER
      initContainers:
        - name: wait-for-redis
          image: busybox
          command: ['sh', '-c', 'until nc -z uvc-redis-srv 6379; do echo "Warte auf Redis..."; sleep 2; done;']
        - name: migration
          image: REGISTRY_URL_PLACEHOLDER/uvc-tenant:latest
          env:
            - name: MONGODB_USER
              valueFrom:
                secretKeyRef:
                  name: mongodb-cluster
                  key: user
            - name: MONGODB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongodb-cluster
                  key: password
            - name: MONGODB_URI
              valueFrom:
                secretKeyRef:
                  name: mongodb-cluster
                  key: uri
          command: ["npm", "run", "migrate-up"]
      containers:
        - name: uvc-tenant
          image: REGISTRY_URL_PLACEHOLDER/uvc-tenant:latest
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          ports:
            - containerPort: 3002
          livenessProbe:
            httpGet:
              path: /health
              port: 3002
            initialDelaySeconds: 180
            periodSeconds: 20
            timeoutSeconds: 5
          readinessProbe:
            httpGet:
              path: /health
              port: 3002
            initialDelaySeconds: 5
            periodSeconds: 20
            timeoutSeconds: 5
          env:
            - name: JWT_ENCRYPTION_KEY
              valueFrom:
                secretKeyRef:
                  name: jwt-encryption-key
                  key: schluessel
            - name: MONGODB_USER
              valueFrom:
                secretKeyRef:
                  name: mongodb-cluster
                  key: user
            - name: MONGODB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongodb-cluster
                  key: password
            - name: MONGODB_URI
              valueFrom:
                secretKeyRef:
                  name: mongodb-cluster
                  key: uri
            - name: BREVO_API_KEY
              valueFrom:
                secretKeyRef:
                  name: environment
                  key: brevo_key
            - name: ENVIRONMENT
              valueFrom:
                secretKeyRef:
                  name: environment
                  key: mode
            - name: PUBLIC_URL
              valueFrom:
                secretKeyRef:
                  name: environment
                  key: public_url
            - name: NETWORK_KEY
              valueFrom:
                secretKeyRef:
                  name: environment
                  key: network_key
---
apiVersion: v1
kind: Service
metadata:
  name: uvc-tenant-srv
spec:
  selector:
    app: uvc-tenant
  ports:
    - name: uvc-tenant
      protocol: TCP
      port: 3002
      targetPort: 3002