apiVersion: apps/v1
kind: Deployment
metadata: 
  name: uvc-calendar
spec:
  replicas: 1
  selector: 
    matchLabels: 
      app: uvc-calendar
  template:
    metadata:
      labels:
        app: uvc-calendar
    spec:
      imagePullSecrets:
        - name: REGISTRY_SECRET_PLACEHOLDER
      initContainers:
        - name: wait-for-redis
          image: busybox
          command: ['sh', '-c', 'until nc -z uvc-redis-srv 6379; do echo "Warte auf Redis..."; sleep 2; done;']
        - name: migration
          image: REGISTRY_URL_PLACEHOLDER/uvc-calendar:latest
          env:
            - name: MONGODB_USER
              valueFrom:
                secretKeyRef:
                  name: mongodb-cluster
                  key: user
            - name: MONGODB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongodb-cluster
                  key: password
            - name: MONGODB_URI
              valueFrom:
                secretKeyRef:
                  name: mongodb-cluster
                  key: uri
          command: ["npm", "run", "migrate-up"]
      containers:
        - name: uvc-calendar
          image: REGISTRY_URL_PLACEHOLDER/uvc-calendar:latest
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          ports:
            - containerPort: 3004
          livenessProbe:
            httpGet:
              path: /health
              port: 3004
            initialDelaySeconds: 180
            periodSeconds: 20
            timeoutSeconds: 5
          readinessProbe:
            httpGet:
              path: /health
              port: 3004
            initialDelaySeconds: 5
            periodSeconds: 20
            timeoutSeconds: 5
          env:
            - name: JWT_ENCRYPTION_KEY
              valueFrom:
                secretKeyRef:
                  name: jwt-encryption-key
                  key: schluessel
            - name: MONGODB_USER
              valueFrom:
                secretKeyRef:
                  name: mongodb-cluster
                  key: user
            - name: MONGODB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongodb-cluster
                  key: password
            - name: MONGODB_URI
              valueFrom:
                secretKeyRef:
                  name: mongodb-cluster
                  key: uri
            - name: ENVIRONMENT
              valueFrom:
                secretKeyRef:
                  name: environment
                  key: mode
            - name: PUBLIC_URL
              valueFrom:
                secretKeyRef:
                  name: environment
                  key: public_url
            - name: S3_ENDPOINT_URL
              valueFrom:
                secretKeyRef:
                  name: s3-config
                  key: endpoint_url
            - name: S3_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: s3-config
                  key: access_key
            - name: S3_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: s3-config
                  key: secret_key
            - name: S3_BUCKET_NAME
              valueFrom:
                secretKeyRef:
                  name: s3-config
                  key: bucket_name
            - name: NETWORK_KEY
              valueFrom:
                secretKeyRef:
                  name: environment
                  key: network_key
---
apiVersion: v1
kind: Service
metadata:
  name: uvc-calendar-srv
spec:
  selector:
    app: uvc-calendar
  ports:
    - name: uvc-calendar
      protocol: TCP
      port: 3004
      targetPort: 3004