import { GROUP_PERMISSION_LEVEL, Groups } from "@eduinteractive/uvc-api"


const permissionMap = {
    "tenant:administration": [GROUP_PERMISSION_LEVEL.ADMIN],
    "member:administration": [GROUP_PERMISSION_LEVEL.ADMIN],
    "calendar:create": [GROUP_PERMISSION_LEVEL.ADMIN, GROUP_PERMISSION_LEVEL.MODERATOR, GROUP_PERMISSION_LEVEL.MEMBER],
    "calendar:edit": [GROUP_PERMISSION_LEVEL.ADMIN, GROUP_PERMISSION_LEVEL.MODERATOR],
    "calendar:delete": [GROUP_PERMISSION_LEVEL.ADMIN, GROUP_PERMISSION_LEVEL.MODERATOR],
    "profile:update": [GROUP_PERMISSION_LEVEL.ADMIN, GROUP_PERMISSION_LEVEL.MODERATOR],
    "profile_objects:create": [GROUP_PERMISSION_LEVEL.ADMIN, GROUP_PERMISSION_LEVEL.MODERATOR, GROUP_PERMISSION_LEVEL.MEMBER],
    "profile_objects:edit": [GROUP_PERMISSION_LEVEL.ADMIN, GROUP_PERMISSION_LEVEL.MODERATOR],
    "profile_objects:delete": [GROUP_PERMISSION_LEVEL.ADMIN, GROUP_PERMISSION_LEVEL.MODERATOR],
    "profile_objects:publish": [GROUP_PERMISSION_LEVEL.ADMIN, GROUP_PERMISSION_LEVEL.MODERATOR],
    "budget:create": [GROUP_PERMISSION_LEVEL.ADMIN, GROUP_PERMISSION_LEVEL.MODERATOR, GROUP_PERMISSION_LEVEL.MEMBER],
    "budget:edit": [GROUP_PERMISSION_LEVEL.ADMIN, GROUP_PERMISSION_LEVEL.MODERATOR],
    "budget:delete": [GROUP_PERMISSION_LEVEL.ADMIN, GROUP_PERMISSION_LEVEL.MODERATOR],
    "knowledge:create": [GROUP_PERMISSION_LEVEL.ADMIN, GROUP_PERMISSION_LEVEL.MODERATOR, GROUP_PERMISSION_LEVEL.MEMBER],
    "knowledge:edit": [GROUP_PERMISSION_LEVEL.ADMIN, GROUP_PERMISSION_LEVEL.MODERATOR],
    "knowledge:delete": [GROUP_PERMISSION_LEVEL.ADMIN, GROUP_PERMISSION_LEVEL.MODERATOR],
    "survey:create": [GROUP_PERMISSION_LEVEL.ADMIN, GROUP_PERMISSION_LEVEL.MODERATOR, GROUP_PERMISSION_LEVEL.MEMBER],
    "survey:edit": [GROUP_PERMISSION_LEVEL.ADMIN, GROUP_PERMISSION_LEVEL.MODERATOR],
    "survey:delete": [GROUP_PERMISSION_LEVEL.ADMIN, GROUP_PERMISSION_LEVEL.MODERATOR],
    "chat:create": [GROUP_PERMISSION_LEVEL.ADMIN, GROUP_PERMISSION_LEVEL.MODERATOR, GROUP_PERMISSION_LEVEL.MEMBER, GROUP_PERMISSION_LEVEL.GUEST],
    "chat:delete": [GROUP_PERMISSION_LEVEL.ADMIN, GROUP_PERMISSION_LEVEL.MODERATOR],
    "notifications:delete": [GROUP_PERMISSION_LEVEL.ADMIN, GROUP_PERMISSION_LEVEL.MODERATOR],
    "event:create": [GROUP_PERMISSION_LEVEL.ADMIN, GROUP_PERMISSION_LEVEL.MODERATOR, GROUP_PERMISSION_LEVEL.MEMBER],
    "event:edit": [GROUP_PERMISSION_LEVEL.ADMIN, GROUP_PERMISSION_LEVEL.MODERATOR],
    "event:delete": [GROUP_PERMISSION_LEVEL.ADMIN, GROUP_PERMISSION_LEVEL.MODERATOR],
    "project:create": [GROUP_PERMISSION_LEVEL.ADMIN, GROUP_PERMISSION_LEVEL.MODERATOR, GROUP_PERMISSION_LEVEL.MEMBER],
    "project:edit": [GROUP_PERMISSION_LEVEL.ADMIN, GROUP_PERMISSION_LEVEL.MODERATOR],
    "project:delete": [GROUP_PERMISSION_LEVEL.ADMIN, GROUP_PERMISSION_LEVEL.MODERATOR],
}

export const checkPermission = (group: Groups, acl: string) => {
    const permission = permissionMap[acl as keyof typeof permissionMap]
    if (permission) {
        return permission.find((p) => p === group.permissionLevel) !== undefined
    } else {
        return false
    }
}